name: Generate changelog

on: 
  workflow_dispatch:
  push:

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate
        id: generate
        uses: tahirmt/changelog-generator-linux@main
        with:
          since: 'v1.0.1'
          nextTag: 'next_tag_value'
          filter: 'filter_regex'
          labels: 'labels,comma,separated'

      - name: Check output
        run: |
          changelog=$(echo "${{ steps.generate.outputs.changelog }}" | base64 --decode)
          echo "------ CHANGELOG ------"
          echo "$changelog"
