name: Generate changelog

on: 
  workflow_dispatch:
  push:

jobs:
  changelog:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate
        uses: tahirmt/test-simple-github-action@master
        with:
          token: 'token_value'
          outputFile: 'output_file_value'
          since: 'since_value'
          nextTag: 'next_tag_value'
          filter: 'filter_regex'
          labels: 'labels,comma,separated'
