name: Generate changelog

on: 
  workflow_dispatch:
  push:

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate
        id: generate
        uses: tahirmt/test-simple-github-action@master
        with:
          outputFile: './output_file_value.md'
          since: 'v1.0.1'
          nextTag: 'next_tag_value'
          filter: 'filter_regex'
          labels: 'labels,comma,separated'

      - name: Check output
        run: |
          changelog=${{ steps.generate.outputs.changelog }}

          echo "------ CHANGELOG ------"
          echo $changelog
