name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
        # path to file that contains the POST response of the event
    # Example: https://github.com/actions/bin/tree/master/debug
    # Value: /github/workflow/event.json

    if [[ ! -f "${GITHUB_EVENT_PATH}" ]]; then
        echo "can not find github events file in GITHUB_EVENT_PATH ${GITHUB_EVENT_PATH}";
        exit 1;
    fi
    echo "using github events file in GITHUB_EVENT_PATH ${GITHUB_EVENT_PATH}";
