name: Swift

on:
  push:
  pull_request:
    types:
      - synchronize

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        one: ['one', 'two']
        two: ['one', 'two']
    runs-on: ubuntu-latest

    steps:
    - name: Set status
      if: matrix.one == 'one' && github.ref == 'refs/heads/testing-workflow'
      id: status
      run: |
        echo "::set-output name=status::skipped"

    - uses: actions/checkout@v2
    - name: Say hello
      if: steps.status.outputs.status != 'skipped'
      run: echo "hello"
    
    - name: Event
      run: |
        echo "github event: ${{ github.event_name }}"
